version: 3
endpoint: https://next-mudfish-55.hasura.app
admin_secret: dbtKIKiADj10AeNG76Ukv1YOMAHFlAxUBiUyPuK3syOVsD7b0enUr4vI9DiF53Mv
metadata_directory: metadata
actions:
  kind: synchronous
  handler_webhook_baseurl: http://localhost:3000
