name: 'build-test'
on:
  pull_request:
    types: [open, reopen, synchronize]
  push:
    branches:
      - main

jobs:
  preview: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: hasura/hasura-cloud-preview-apps@v0.0.2
        with:
          name: 'preview-app-${{github.event.number}}'
          hasuraCloudGraphQLEndpoint: 'https://perfect-cobra-37.hasura.app/v1/graphql'
          hasuraProjectDirectoryPath: hasura
          region: 'ap-south-1'
          hasuraEnv: |
            HASURA_GRAPHQL_CORS_DOMAIN=*
            HASURA_GRAPHQL_ADMIN_SECRET=EvWrgJdVwtzBf93zC0snXWytEdGQLVBK9RpVnwLeCIco7euydoZyxdxCmeyiLy72
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          HASURA_CLOUD_ACCESS_TOKEN: ${{secrets.HASURA_CLOUD_ACCESS_TOKEN}}
          ACTIONS_RUNNER_DEBUG: true
